### PR TITLE
Proposal: automate Obsidian API documentation

### PR DESCRIPTION
**Pull request by LBF38**
Hello the Obsidian team !

This PR is a proposal to update the automatic documentation of the Obsidian APIs.
As stated inside the config/README, it would be better to have a direct and auto generated documentation from the updated Obsidian API. 
Therefore, I have added the Obsidian API as a submodule and moved the api-extractor config inside of it.

Moreover, I have changed the `gendoc.sh` script to call the relative repos and changed the relative paths for generating the TypeScript API documentation.
As the documentation is now automatically generated, I have also ignored it from Git.

## Changes 
- Add `obsidian-api` as a git submodule
- Update `gendoc.sh` to work locally and automatically generate the TypeScript API documentation.
- Add `TypeScript API` folder to `.gitignore` and removed it from git cache.

## Updates of the `gendoc.sh`
To be able to run the script locally, I need the `api-documenter` binary modified for Obsidian's documentation purposes. Therefore, I have made a fork of [ericaxu/rushstack-obsidian](https://github.com/ericaxu/rushstack-obsidian) (https://github.com/LBF38/rushstack-obsidian) to add an automatic release workflow whenever the Obsidian api-documenter is updated.
Moreover, in the script, we can then download the binary in order to build the documentation locally.
However, it is on this part that I haven't successfully achieved it. It seems that the `api-documenter` binary calls some modules and is not standalone. If you know how to make it standalone, it would be perfect for the usecase.
(I have also inspired myself from the `build_typescript_docs` gh actions workflow).

I hope it would help to improve the overall documentation of the Obsidian's API !

## Important links
One important link is the PR I have made to the https://github.com/obsidianmd/obsidian-api in order to make it work.
Here it is : https://github.com/obsidianmd/obsidian-api/pull/127

### CODE REVIEW

**Comment by lishid** [comment]
I don't think it's a good idea to use git submodules, instead I would suggest importing the .d.ts file via npm and updating it using package.json.

**Comment by LBF38** [comment]
The Git submodule isn't really heavyweight, but I agree, we can fetch the npm package and build from there. Then, remove it at the end if necessary.

Moreover, the api-extractor.json wouldn't be added to the obsidian-api, thus it wouldn't create a mess in the npm package when publishing.

**Comment by LBF38** [comment]
By the way, do you know how to correctly build the api-documenter in a standalone package or somewhat ? 

Because I have tried a lot of things, from the Obsidian fork and didn't manage to have anything working correctly.. 
On top of that, the rushstack monorepo is really heavy.

Maybe @ericaxu knows how to manage it ?

**Comment by lishid** [comment]
Hmm I am not quite familiar, I just know that it runs in a github action that indeed takes a long time because rushstack is so large and heavy.

**Comment by LBF38** [comment]
@lishid please see the updated PR, hope it fits !

I have removed the git submodule and changed it to the obsidian package.
Therefore, the build is automatically retrieving the latest version of obsidian and creating the docs from this one.

Moreover, I managed to create the Obsidian version of `api-documenter` using GH Packages. So, it uses this one in the modified and updated version of the `gendoc.sh` script.

I don't know all the details about how the API documentation should look like, so please review it and feel free to modify things !

PS: I have noticed that the generated API documentation has aliases in each note, in the format `<object/class name>.<property>.<more things>`, but they aren't correctly resolved in Obsidian (the file are told to not be created yet). Is this normal ?

**Comment by joethei** [comment]
Hi, we have found another, simpler way and implemented it.

Thank you for your work either way.

**Pull request closed without merging**
