### PR TITLE
Fix "Update Use React in your plugin" code snippet

### PR DESCRIPTION
**Pull request by nirtamir2**
This PR fix code snippet in [Update Use React in your plugin](https://docs.obsidian.md/Plugins/Getting+started/Use+React+in+your+plugin#Create+an+App+context) page.
`root.render` does have a single param. See https://react.dev/reference/react-dom/client/createRoot#root-render

### CODE REVIEW

**Comment by nirtamir2** [comment]
I notice now that my code refers to react 18 while I think the example code used an outdated version of react. So we might change unmount component at node too

**Comment by ericaxu** [comment]
> I notice now that my code refers to react 18 while I think the example code used an outdated version of react. So we might change unmount component at node too

Ok sure thing! Do you want to change that in the same PR or a different PR?

**Comment by ericaxu** [comment]
Gentle ping @nirtamir2  should we merge this for now?

**Comment by nirtamir2** [comment]
I've updated my branch. Can you review the changes? I change to react 18 and the new docs

**Comment by ericaxu** [comment]
Thank you!!

**Pull request merged**
